### ISSUE TITLE
Howto Contribute ?

### ISSUE THREAD

**Issue by NebzHB** [grover/homebridge-ranger#1]
Hello, i see your project have Eve energy only, if needed I own Eve Motion, Eve Door&Window, Eve Room, Eve thermo, Eve Weather. How may I contribute ?

**Comment by grover** [comment]
Hi,

there's a new version in the works, which should provide support for all Eve devices. I've to wait for HAP-NodeJS/Homebridge to update and include my pull request https://github.com/KhaosT/HAP-NodeJS/pull/542

After I publish the next one, it would be great if you can support me in testing. Specifically I can't test an eve motion and weather. I'm interested how these perform over time.

Thanks!

**Comment by grover** [comment]
I've pushed version 0.3.0 of the plugin with support for Eve Door&Window, Eve Thermo. Give it a try and send me some feedback. Thanks!

**Comment by grover** [comment]
I've been using this plugin for 3 weeks now with Thermo / Door & Window. No issues so far.
