### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by ScrewedDK** [grover/homebridge-ranger#13]
I tried installing but along the way I got this error code. Can you hep me? I have tried installing git as instructed in another issue..

My goal is to connect an Eve Aqua located at a great distance from my hub, so I hope you guys can help. :-) 

npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b connection-interval-test git://github.com/grover/noble.git /root/.npm/_cacache/tmp/git-clone-4336d054
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-4336d054': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-05T17_37_59_826Z-debug.log
child_process.js:614
    throw err;
    ^

Error: Command failed: npm install --no-save github:grover/noble#730865a5152d6d767a2d1413c0c27eac4bde3df5 --unsafe-perm
    at checkExecSyncError (child_process.js:574:11)
    at Object.execSync (child_process.js:611:13)
    at Object.<anonymous> (/opt/node-v9.3.0-linux-armv7l/lib/node_modules/homebridge-ranger/install_dependencies.js:35:17)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/homebridge-ranger/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-ranger@0.3.2 install: `node install_dependencies.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge-ranger@0.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-05T17_38_06_652Z-debug.log

**Comment by tperamaki** [comment]
`sudo -i` fixed this for me too, seems like the `install_dependencies.js` might not be run with sudo when running the main step with sudo, but when running it as sudo it works as everything is run as sudo.

**Comment by grover** [comment]
I removed the dependency to my custom noble version with release 0.3.4 - this should now be fixed.

**Comment by grover** [comment]
Closing. #16 provides troubleshooting instructions, which I’ll add to the docs.
