### ISSUE TITLE
Not discovering new devices

### ISSUE THREAD

**Issue by jcvangent** [grover/homebridge-ranger#15]
So I updated to 0.3.3 today, everything is fine and the current devices are all still working :-)

However, I have an Eve Thermo (version 1) that I want to connect, I unpaired it from the Eve app, did a full reset on the Thermo so it is ready to be paired to the homebridge-ranger.

However, I'm not seeing any "Found unpaired accessory" statement whatsoever popping up in the log file. Just the same information that was there before when I restart homebridge (even with debug mode on, there is nothing)

Did something change as a result of the changes you made that made it to bump this version that it doesn't discover new devices anymore?

I even tried moving the Raspberry Pi to 50cm's of the Eve Thermo to maybe help discover it, but nothing.

Let me know if you want some more information to help to debug this one, although there is nothing of interest really in the logfile from what I can tell.

**Comment by samgeorge** [comment]
Yes.

Same issue - reported as a separate issue.

**Comment by JBelinchon** [comment]
Hi, I have a similar issue with my Eve Door device.
I have a RPI 3 Model B, running raspbian.
node v9.3.0
npm v5.5.1
homebridge 0.4.46

running `hcitool lescan`  it founds the sensor:

```
root@raspberrypi:~# hcitool lescan
LE Scan ...
D6:7B:8F:B5:4A:6A Eve
D6:7B:8F:B5:4A:6A Eve Door F4A5
```
After unpair and hard reset the device I run hombridge. but it can not find the device:

```
root@raspberrypi:~# /opt/node/bin/homebridge -D -U /var/lib/homebridge/
[2019-3-10 03:43:08] Loaded config.json with 0 accessories and 1 platforms.
[2019-3-10 03:43:08] ---
[2019-3-10 03:43:08] Loaded plugin: homebridge-ranger
[2019-3-10 03:43:08] Registering platform 'homebridge-ranger.Ranger'
[2019-3-10 03:43:08] ---
[2019-3-10 03:43:08] Loading 1 platforms...
[2019-3-10 03:43:08] [Ranger] Initializing Ranger platform...
[2019-3-10 03:43:08] [Ranger] Ranger Platform Plugin Loaded
[2019-3-10 03:43:08] [Ranger] DidFinishLaunching
Setup Payload:
X-HM://0023OUAZM0EN0
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
[2019-3-10 03:43:09] Homebridge is running on port 51826.
[2019-3-10 03:43:09] [Ranger] Starting to scan for bluetooth devices
^C[2019-3-10 03:43:21] Got SIGINT, shutting down Homebridge...
root@raspberrypi:~#
```

**Comment by jcvangent** [comment]
Yups that is the exact same behaviour I'm seeing @JBelinchon 

NPM version 6.7.0
Node version 9.3.0
Homebridge version 0.4.46
Homebridger ranger version 0.3.3

It worked before, but now I updated to 0.3.3 I've seen this problem for the first time. The other issues for which we found a manual workaround in 0.3.2 are gone and it is working stable now with the already connected devices, but it can't find/pair any new devices

**Comment by jfgarciamex** [comment]
I do have the same issue in a fresh install with pi 3 B+. Hcitool lescan also show my eve devices.
node 9.3.0
npm 5.5.1
Homebridge 0.4.6
Ranger 0.3.3
This is my first setup, so I have no paired devices.

**Comment by jcvangent** [comment]
Maybe it has something to do with this specific commit?

https://github.com/grover/homebridge-ranger/commit/d8fa8d5d5890debf9da28554422efafc6424b089

**Comment by jfgarciamex** [comment]
It may be it. Just removed 0.3.3 and installed 0.3.2 and now its scanning my accessories. Just displayed pair and unpair accessories.

**Comment by jcvangent** [comment]
Yeah but 0.3.2 had all sorts of other issues that I manually had to fix, see this issue: https://github.com/grover/homebridge-ranger/issues/9

so not keen on going back as well. @grover any idea if that specific commit mentioned earlier could be the one thing that is blocking discovering of new devices?

**Comment by grover** [comment]
I’ll take a look during the week.

**Comment by jfgarciamex** [comment]
Yes... 0.3.2 is giving me all kind of problems... I guess, I need to wait for 0.3.3 to be fixed...

**Comment by jcvangent** [comment]
Thanks a lot @grover, much appreciated!

**Comment by grover** [comment]
New release 0.3.4 is out. In my tests it fixed the issue, no significant changes beyond this.

**Comment by samgeorge** [comment]
Confirmed on #9 - working as expected.

**Comment by grover** [comment]
Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
