### ISSUE TITLE
Homebridge-Ranger Installations Commando

### ISSUE THREAD

**Issue by iDominik94** [grover/homebridge-ranger#3]
Hallo Grover!

Ich habe mir das gleiche Raspberry angelegt wie in der Readme beschrieben. Soweit komme ich auch mit der Installation voran, jedoch gibt der Befehl, der das Plugin homebridge-ranger installieren soll einen Fehler aus. Kannst du das nachvollziehen?

Viele Grüße
Dominik
![bildschirmfoto 2018-03-20 um 17 16 54](https://user-images.githubusercontent.com/37590161/37667712-eb0e63e8-2c62-11e8-8294-272ec5dfbe24.png)

**Comment by grover** [comment]
Let's keep this in english please.

I didn't encounter your specific issue before. Since it seems like the installation has failed somehow, I'd remove the `/opt/node-v9.3.0-linux-armv6l/lib/node_modules/homebridge-ranger` directory and try installing again. Let's see if that helps.

**Comment by iDominik94** [comment]
Hey, thanks for your answer. The directory doesn't exists on my installation. I got the same error after the uuid command / process. 
<img width="682" alt="bildschirmfoto 2018-03-21 um 13 46 16" src="https://user-images.githubusercontent.com/37590161/37710616-6f6d53be-2d0e-11e8-8022-f3677323fc42.png">
