### ISSUE TITLE
Installation schlägt fehl

### ISSUE THREAD

**Issue by Bankaifan** [grover/homebridge-ranger#4]
Hi Grover,

ich habe anhand der Anleitung versucht, Homebridge-Ranger zu installieren. 

Mit diesem Command: sudo npm install -g homebridge-ranger --unsafe-perm

Danach startet dieses GYP-Zeug bis diese Meldung kommt

> usb@1.3.1 install /usr/local/lib/node_modules/homebridge-ranger/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-node-v59-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for usb@1.3.1 and node@9.11.1 (node-v59 ABI, glibc) (falling back to source compile with node-gyp) 
make: Verzeichnis „/usr/local/lib/node_modules/homebridge-ranger/node_modules/usb/build“ wird betreten

Danach läuft es weiter bis zum Fehler

> homebridge-ranger@0.3.2 install /usr/local/lib/node_modules/homebridge-ranger
> node install_dependencies.js

npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b connection-interval-test git://github.com/grover/noble.git /root/.npm/_cacache/tmp/git-clone-f517d9dc
npm ERR! /root/.npm/_cacache/tmp/git-clone-f517d9dc/.git: Keine Berechtigung
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-05T11_40_07_066Z-debug.log
child_process.js:615
    throw err;
    ^

Error: Command failed: npm install --no-save github:grover/noble#730865a5152d6d767a2d1413c0c27eac4bde3df5 --unsafe-perm
    at checkExecSyncError (child_process.js:575:11)
    at Object.execSync (child_process.js:612:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ranger/install_dependencies.js:35:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/homebridge-ranger/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-ranger@0.3.2 install: `node install_dependencies.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge-ranger@0.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-05T11_40_09_826Z-debug.log

**Comment by nikolaykasyanov** [comment]
I have the same problem, it looks like `npm install --no-save github:grover/noble#730865a5152d6d767a2d1413c0c27eac4bde3df5 --unsafe-perm` is performed without `sudo`.

**Comment by nikolaykasyanov** [comment]
I've found some [similar](https://github.com/KraigM/homebridge-harmonyhub/issues/97) [issues](https://github.com/KraigM/homebridge-harmonyhub/issues/119), downgrading npm to 4.* fixes the issue.

**Comment by Samuel3** [comment]
I had the same issue with npm 6.4.1 what worked for me was running bash with ```su```

**Comment by palasinio** [comment]
Have you checked, if this is fixed with nem 6.5.0?

**Comment by palasinio** [comment]
Hi, it installs NOT with npm 6.5.0, 6.4.0, 5.6.0, 5.5.1 (comes with node 9.3.0) as far as I have tested.
Install as root (sudo su) may help in these cases.
It installs with node 9 and npm 4.6.1.

**Comment by grover** [comment]
I removed the dependency to my custom noble version with release 0.3.4 - this should now be fixed.

**Comment by grover** [comment]
Closing. #16 provides troubleshooting instructions, which I’ll add to the docs.
