### ISSUE TITLE
Unpairing eve door contact 

### ISSUE THREAD

**Issue by ceraz68** [grover/homebridge-ranger#5]
Hi Grover, great job on this plugin. I installed the plugin on a 2006 mac mini with an ASUS BT400 dongle. I followed the recommendation to run this on a dedicated home bridge server as I run my main Homebridge server on a synology.

I have an eve contact that is just on the limit of my ATV4 bluetooth range. Connectivity is unreliable when away from home as the ATV4 is my homekit hub. I want to increase connection reliability with your plugin as the eve contact is only a few metres from my mac mini (the ATV4 is 8m away behind concrete walls).

After the plugin BT scan, the contact is identified as already being paired (probably my ATV or IOS device). In your doc you say: "Make sure that the accessory you want to pair reports as unpaired. The plugin will not pair with accessories that are already paired to a different controller."

1) So my first question is how to unpair the eve with the other devices so I can pair it with the plugin?
2) Secondly, if homebridge crashes/restarts do you know if the eve will "re-"pair with the other devices that would be within range?

Thanks

PS: initially the eve contact was added as an homekit accessory via the IOS home and Eve apps

**Comment by grover** [comment]
Hi, 

1. just remove it from the Home app or the Eve app. You can do this through the Settings, Devices in the Eve app. That's all that's required. If it shows up on the list of devices, when you try to add a new one in Eve, it's not paired. That's what you want.

2. It will not pair by itself unless someone manually enters the 9 digit code or scans the code on the device. You're fine in this regard, but events that happen while homebridge is down are likely lost.

I hope this helps.

**Comment by ceraz68** [comment]
Thanks a lot worked like a charm, very useful plugin , well done!
