### ISSUE TITLE
Works fine with Eve Room (1st gen)

### ISSUE THREAD

**Issue by ozaoral** [grover/homebridge-ranger#8]
I can confirm that Ranger works well with Eve Room (1st generation, the white "box"), sw v. 1.3.1 (466). The accessory was regularly shown as unresponsive in both the Eve app and Apple Home app, using extended config worked well - after increasing timeout, all works like a snap :) 

Config example 

```
"name": "Eve Dining Room",
"address": "c7:15:5e:3f:06:56",
"pin": "123-45-678",
"reachability": "true",
"reachabilityTimeout": "120000",
"rssi": "false"
```

**Comment by grover** [comment]
Thanks!
